version: "3.8"

services:
  mongodb-user:
    image: mongo
    container_name: mongodb-user
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ixml
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo-user-data:/data/db
    networks:
      - utopis-networks

  mongo-expres:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ixml
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongodb-user
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    networks:
      - utopis-networks

networks:
  utopis-networks:
    driver: bridge

volumes:
  mongo-user-data:
